### ISSUE TITLE
Error Cannot GET /

### ISSUE THREAD

**Issue by JacobKre** [foucdeg/airspaces#15]
Heya,
This looks like an amazing app but whenever I try to access it from my browser at localhost:9000 I get an error that says "Cannot GET /" (Screenshot Attached) Any help would be appreciated! I have enabled the settings in X-Plane 11 on lines 20 & 104 with the IP as 127.0.01 and the port as 49003.
Thanks,
Jacob
![Screenshot_1](https://user-images.githubusercontent.com/70914399/111397144-ef1fff00-8696-11eb-83f6-a8ab571e5344.png)

**Comment by foucdeg** [comment]
Hey Jacob,
Maybe this is a copy-paste issue but the IP is `127.0.0.1` (note the dot before the 0).
Did you try to use the public online Airspace at public.airspaces.app first ?

**Comment by foucdeg** [comment]
Actually, port 9000 is the API. This response on `/` is expected.

If you're running the Docker image, it doesn't serve the frontend client, you need to run it separately (by following the README on Github for the frontend parts)
If you're running the app from the instructions on the README on Github, the client should be accessible on port 3000 (not 9000).

**Comment by JacobKre** [comment]
I'll give that a shot right now! I wasn't running the frontend part so that is probably the issue. I'll keep you updated!

**Comment by JacobKre** [comment]
Alrighty, so when trying to run the frontend I got this 
![image](https://user-images.githubusercontent.com/70914399/111555580-14784000-875f-11eb-8dd8-bdb07b39d80a.png)

**Comment by foucdeg** [comment]
Oh, you're on Windows. Things should be able to work but you need to slightly edit the package.json file: in the "scripts" section, under "start", change it to "`set REACT_APP_ENV=local && react-app-rewired start`". This is the Windows syntax for setting inline envirnoment variables which is different from the Linux / Mac syntax.

**Comment by foucdeg** [comment]
I'm still wondering whether you gave the hosted version at public.airspaces.app a try ? If you don't mind other people seeing where you're flying, it's definitely the easiest way.

**Comment by JacobKre** [comment]
It works perfectly now! It looks like it was fixed by changing that one line in the package.json. Thanks for the help!

**Comment by JacobKre** [comment]
It works perfectly now! It looks like it was fixed by changing that one line in the package.json. Thanks for the help!
