### ISSUE TITLE
blocage d'Airspaces ?

### ISSUE THREAD

**Issue by marcopol2211** [foucdeg/airspaces#18]
apparemment depuis 2 jours, ( 13-14 avril 2021) impossible d'avoir mon avion sur Airspaces public , ( ainsi que les autres en visuel d'ailleurs) 
mes paramètres d'accès sont bons car je l'utilise couramment.
merci de votre réponse
marcopol

apparently for 2 days, (April 13-14, 2021) impossible to have my plane on public Airspaces, (as well as the others in visual for that matter)
my access settings are good because I use it fluently.
Thank you for your reply
marcopol

**Comment by foucdeg** [comment]
Bonjour, désolé de l'interruption dûe à un souci de paiement chez OVH. C'est rétabli depuis quelques jours.

**Comment by marcopol2211** [comment]
Yes I have see.. 
Thank you
