### ISSUE TITLE
Airspaces.app

### ISSUE THREAD

**Issue by backgarden01** [foucdeg/airspaces#39]
Hi Everybody 
Are any of you experiencing Airspaces.app, not working.
For the past week, when I open it up, it is showing no aircraft at all, anywhere in the world, and it opens up looking at the ocean, of the west coast of Africa, which is not normal.

Thanks for any help.

**Comment by user123user123** [comment]
Hello!
Yep, I got exactly the same problem

**Comment by backgarden01** [comment]
Hi

I wonder what the problem is, you are the only other person who has responded.

Regards Steve
(Sent from my ipad)

On 29 Aug 2022, at 17:30, user123user123 ***@***.***> wrote:

﻿

Hello!
Yep, I got exactly the same problem

**Comment by user123user123** [comment]
Yep, I just hope this incredible app will start working again, it gives such an amazing experience  being connected to xplane)

**Comment by patrickmamaid** [comment]
Hey everyone,

I have airspaces pulled down running locally for a while and it runs fine w/ X-Plane 11 and 12
I can share my setup publicly while airspaces.app is down:

UI: https://airspaces.sysbox.ca

Send UDP to: `104.248.110.91` Port: `49003`
L104:transponderstatus and L20:lat/long/alt


Thought I could contribute a little bit :) 

Pat

**Comment by backgarden01** [comment]
Thanks Pat, I will give it try.

Steve
Sent from my iPhone

On 10 Sep 2022, at 11:43, Patrick Mamaid ***@***.******@***.***>> wrote:


Hey everyone,

I have airspaces pulled down running locally for a while and it runs fine w/ X-Plane 11 and 12
I can share my setup publicly while airspaces.app is down:

UI: https://airspaces.sysbox.ca

Send UDP to: 104.248.110.91 Port: 49003
L104:transponderstatus and L20:lat/long/alt

Thought I could contribute a little bit :)

Pat

**Comment by user123user123** [comment]
> 



> Hey everyone,
> 
> I have airspaces pulled down running locally for a while and it runs fine w/ X-Plane 11 and 12 I can share my cloud setup publicly while airspaces.app is down:
> 
> UI: https://airspaces.sysbox.ca
> 
> Send UDP to: `104.248.110.91` Port: `49003` L104:transponderstatus and L20:lat/long/alt
> 
> Thought I could contribute a little bit :)
> 
> Pat
> 
> Whats missing:
> 
> * flightplandatabase airport localizer and waypoints layer needs a fix -- added to my todo to fix soon

Thank you very much, patrickmamaid! It works perfectly!

**Comment by backgarden01** [comment]
Thanks Patrick for that info, it works perfectly on my system as well

**Comment by pete80602** [comment]
> Hey everyone,
> 
> I have airspaces pulled down running locally for a while and it runs fine w/ X-Plane 11 and 12 I can share my cloud setup publicly while airspaces.app is down:
> 
> UI: https://airspaces.sysbox.ca
> 
> Send UDP to: `104.248.110.91` Port: `49003` L104:transponderstatus and L20:lat/long/alt
> 
> Thought I could contribute a little bit :)
> 
> Pat
> 
> Whats missing:
> 
> * flightplandatabase airport localizer and waypoints layer needs a fix -- added to my todo to fix soon

Thanks! If I may, I'll give it a try as well.

Pete

**Comment by foucdeg** [comment]
Hi all,
I'm sorry Airspaces was down.
Something must have caused the server to get killed, maybe a reboot.
Thanks @patrickmamaid for saving the day. Airspaces is back up now.

**Comment by pete80602** [comment]
So good to hear!

Airspaces is such an elegant focused app that improves and enhances the quality of my X-Plane experience. In addition to using Airspaces to monitor my flights, I have used it for logging my flights but capturing screenshots after the flight.

So I’m happy and grateful to have it back

Thank you!


Pete

cell  303.332.6082

Don't tell me the sky's the limit when I know that there are footprints on the Moon! — Paul Brandt (with variation)

The work you do while you procrastinate is probably the work you should be doing the rest of your life. — Jessica Hische

Ipsa scientia potesta est — Knowledge itself is power. — Francis Bacon

**Comment by backgarden01** [comment]
Great news - this is such a handy app, when using X plane, I particularly use it to navigate around airport taxiways, but it’s nice to track where you are on the map as well
Well done bringing it back up.

**Comment by patrickmamaid** [comment]
Awesome! glad to have you back and appreciate the work you've done having this up for all of us!
-- closing down the unneeded vm now :)

**Comment by backgarden01** [comment]
Hi Patrick

Tried out your suggestion in my x plane 12, and it worked perfect, thanks for the help and suggestion.

Regards Steve
(Sent from my ipad)

On 10 Sep 2022, at 11:43, Patrick Mamaid ***@***.***> wrote:

﻿

Hey everyone,

I have airspaces pulled down running locally for a while and it runs fine w/ X-Plane 11 and 12
I can share my setup publicly while airspaces.app is down:

UI: https://airspaces.sysbox.ca

Send UDP to: 104.248.110.91 Port: 49003
L104:transponderstatus and L20:lat/long/alt

Thought I could contribute a little bit :)

Pat
